export const AppRoutes = {
  HOME: "/home",
  BASEURL: "/",
  REGISTER: "/auth",
  GEMINI: "/gemini",
  REGISTERPROFILE: "/enter-personal-details",
  REGISTERLOCATION: "/add-your-skills",
  REGISTEJOB: "/enter-job-title",
  UPLOADPROFILEIMAGE: "/upload-profile-image",
  MYNETWORK: "/my-network",
  MESSAGING: "/messaging",
  NOTIFICATIONS: "/notifications",
  FORBUSINESS: "/for-business",
  PROFILE: "/profiles/me",
  // PROFILE: "/profile",
  LOGIN: "/login",

  ADMIN: "/admin-dashboard",
  ADMINMANAGEPROFILES: "/admin-profiles",
  ADMINSETTINGS: "/admin-settings",
  EDITUSER: "/edit-user",
};
