export const AppRoutes = {
  HOME: "/home",
  BASEURL: "/",
  REGISTER: "/auth",
  GEMINI: "/gemini",
  REGISTERPROFILE: "/enter-personal-details",
  REGISTERLOCATION: "/enter-location",
  REGISTEJOB: "/enter-job-title",
  UPLOADPROFILEIMAGE: "/upload-profile-image",
  MYNETWORK: "/my-network",
  MESSAGING: "/messaging",
  NOTIFICATIONS: "/notifications",
  FORBUSINESS: "/for-business",
  PROFILE: "/profile",
  LOGIN: "/login",
};
